[package]
name = "ramsey_theory"
version = "0.1.0"
edition = "2024"
authors = ["Romain Ageron <ageron.r@gmail.com>"]

[dependencies]
ndarray = { version = "0.16.1", optional = true }
rand = "0.8.5"

[features]
default = []
ndarray = ["dep:ndarray"]
